In [1]:
import importlib

import md_Helpers.Logging_Helpers as lh
import md_Helpers.Phase_Separation as ps
import md_Helpers.Sweep_Helpers as sw

importlib.reload(ps)
importlib.reload(lh)
importlib.reload(sw)


# Recalculate phase-separation metadata for all saved V2 randomization runs
phase_report = ps.update_all_v2_phase_separation_metadata(
    nbins=10,
    density_threshold=0.2,
    voxel_fraction_threshold=0.01,
    dry_run=True,
    verbose=True,
)

phase_report

Updating V2 phase-separation metadata
======================================================================
base_folder = /exp/e961/data/MDsims-data/pnichols/Thermalized_States_v2
phase_name = randomization
number of logs found = 133
nbins = 10
density_threshold = 0.2
voxel_fraction_threshold = 0.01
dry_run = True
======================================================================
Processed 25/133 logs
Processed 50/133 logs
Processed 75/133 logs
Processed 100/133 logs
Processed 125/133 logs

Update summary
======================================================================
status
dry_run    133
Name: count, dtype: int64

Changed counts
changed
False    133
Name: count, dtype: int64

Empty DataFrame
Columns: [n_fcc_cells, target_rho, kT, old_phase_separated, new_phase_separated, low_density_fraction, density_threshold, voxel_fraction_threshold, nbins, status, log_path, state_path]
Index: []

In [2]:
import pandas as pd
phase_report_all = ps.update_all_v2_phase_separation_metadata(
    nbins=10,
    density_threshold=0.2,
    voxel_fraction_threshold=0.01,
    dry_run=True,
    verbose=True,
    show_only_changed=False,
)

failed = phase_report_all[
    phase_report_all["status"] == "failed"
].copy()

pd.set_option("display.max_colwidth", None)
display(failed)

Updating V2 phase-separation metadata
======================================================================
base_folder = /exp/e961/data/MDsims-data/pnichols/Thermalized_States_v2
phase_name = randomization
number of logs found = 134
nbins = 10
density_threshold = 0.2
voxel_fraction_threshold = 0.01
dry_run = True
======================================================================
Processed 25/134 logs
Processed 50/134 logs
Processed 75/134 logs
Processed 100/134 logs
Processed 125/134 logs

Update summary
======================================================================
status
dry_run    133
failed       1
Name: count, dtype: int64

Changed counts
changed
False    133
NaN        1
Name: count, dtype: int64

,status,n_fcc_cells,target_rho,kT,old_phase_separated,new_phase_separated,changed,phase_separated,method,nbins,density_threshold,voxel_fraction_threshold,low_density_fraction,log_path,state_path,error
61,failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,0.2,0.01,NaN,/exp/e961/data/MDsims-data/pnichols/Thermalized_States_v2/FCC/n_cells_30/rho_0.620/kT_0.860/nsteps_1000000/seed_1/randomization_log.hdf5,,FileNotFoundError('Could not find matching GSD state for log: /exp/e961/data/MDsims-data/pnichols/Thermalized_States_v2/FCC/n_cells_30/rho_0.620/kT_0.860/nsteps_1000000/seed_1/randomization_log.hdf5')

In [4]:
import importlib
import pandas as pd

import md_Helpers.Phase_Separation as ps

importlib.reload(ps)

delete_report = ps.delete_failed_phase_runs_from_report(
    phase_report_all,
    dry_run=True,
)

display(delete_report)

deleted: /exp/e961/data/MDsims-data/pnichols/Thermalized_States_v2/FCC/n_cells_30/rho_0.620/kT_0.860/nsteps_1000000/seed_1/randomization_log.hdf5
removed empty folder: /exp/e961/data/MDsims-data/pnichols/Thermalized_States_v2/FCC/n_cells_30/rho_0.620/kT_0.860/nsteps_1000000/seed_1

,log_path,state_path,dry_run,deleted_files,missing_files,removed_folder,error
0,/exp/e961/data/MDsims-data/pnichols/Thermalized_States_v2/FCC/n_cells_30/rho_0.620/kT_0.860/nsteps_1000000/seed_1/randomization_log.hdf5,,False,[/exp/e961/data/MDsims-data/pnichols/Thermalized_States_v2/FCC/n_cells_30/rho_0.620/kT_0.860/nsteps_1000000/seed_1/randomization_log.hdf5],[/exp/e961/data/MDsims-data/pnichols/Thermalized_States_v2/FCC/n_cells_30/rho_0.620/kT_0.860/nsteps_1000000/seed_1/randomization.gsd],/exp/e961/data/MDsims-data/pnichols/Thermalized_States_v2/FCC/n_cells_30/rho_0.620/kT_0.860/nsteps_1000000/seed_1,FileNotFoundError('Could not find matching GSD state for log: /exp/e961/data/MDsims-data/pnichols/Thermalized_States_v2/FCC/n_cells_30/rho_0.620/kT_0.860/nsteps_1000000/seed_1/randomization_log.hdf5')